[meta]
run_name = "TGCN_T30_quantile_fixed_test2020_2024"

[data]
seq_dir = "/xdisk/behrangi/omidzandi/GNNs/gnn_precipitation_retrieval/data/pyg_sequences_tgcn_T030_all_years"
ckpt    = "/xdisk/behrangi/omidzandi/GNNs/gnn_precipitation_retrieval/checkpoints/TGCN_T30_quantiles_train2005_2018_val2019_fixed/last-v1.ckpt"
out_dir = "/xdisk/behrangi/omidzandi/GNNs/gnn_precipitation_retrieval/inference/TGCN_T30_quantile_fixed_test2020_2024"
test_years = [2020, 2024]

[compute]
batch_size = 64
num_workers = 4
amp = true

[transforms]
y_transform = "none"
clamp_min = 0.0

[inference]
tau_sel = [0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95]
save_full_quantiles = true
compute_expected = true
enforce_monotonic = true